
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$_PROJECT"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "projects/$_PROJECT/" ]; then
        cd projects/$_PROJECT
        terraform init -backend-config=config/${_ENV}.conf;
      else
        for dir in projects/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "projects/$_PROJECT/" ]; then
        cd projects/$_PROJECT
        terraform plan -var-file=config/${_ENV}.tfvars 
      else
        for dir in projects/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "projects/$_PROJECT/" ]; then
        cd projects/$_PROJECT      
        terraform apply -var-file=config/${_ENV}.tfvars -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$_PROJECT' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
